### ISSUE TITLE
导入Intelllij后运行出现NoClassDefFoundError问题KafkaProducer

### ISSUE THREAD

**Issue by sunnycomes** [hiddenzzh/kafka_book_demo#1]
您好，我刚入坑Kafka，运行第一章的ConsumerFastStart时，出现如下错误，网上找了半天没有找到解决方案，请问您当初写的时候有遇到这个问题吗，怎么解决的？

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/KafkaProducer
	at com.iovi.ch01.ProducerFastStart.main(ProducerFastStart.java:23)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.producer.KafkaProducer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more

**Comment by hiddenzzh** [comment]
记得添加kafka-client的maven依赖

**Comment by sunnycomes** [comment]
谢谢回复，找到问题了，是我的maven抽风了，用了ali的源之后，所有的项目都出现了NoClassDefFoundError的问题。
